### PR TITLE
Fix error when drag with empty value

### PR DESCRIPTION
**Pull request by thanhngch**
Fix error which https://github.com/jsonform/jsonform/pull/239

### CODE REVIEW

**Comment by thanhngch** [comment]
Add field:
```js
JSONForm.fieldTypes['img_view'] = {
  template: '<%= node.value %>'
};
```
Test which schema:
```js
{
  "schema": {
    "images": {
      "type": "array",
      "items": {
        "type": "object",
        "title": "Hình ảnh",
        "properties": {
          "url": {
            "type": "string",
            "title": "Link to file",
            "description": "",
            "required": true
          },
          "caption": {
            "type": "string",
            "title": "Title",
            "description": "",
            "required": true
          }
        }
      }
    }
  },
  "form": [
    {
      "type": "array",
      "htmlClass": "split-md-4",
      "title": "<img src='{{values.images[].url}}' class='img-preview'/>",
      "items": {
        "type": "section",
        "items": [
          {
            "key": "images[].url",
            "fieldHtmlClass": "popupUrl"
          },
          {
            "type": "img_view",
            "value": "<img src='{{values.images[].url}}' class='img-preview'/>"
          },
          {
            "key": "images[].caption"
          }
        ]
      }
    }
  ],
  "value": {
    "images": [{ "url": "/111", "caption": "" }, { "url": "", "caption": "" }]
  }
}
```

**Comment by thanhngch** [comment]
@tchapi Please check it. This is a bug

**Comment by tchapi** [comment]
Hello
Issue #239 was already fixed by your previous PR, that was merged. Here, it seems that you want to add a new type of tab array with images into the tab. I think this is more a specific feature than a bug, but maybe I haven't understood exactly what is it you're trying to achieve ?

Thanks

**Comment by thanhngch** [comment]
Hi,
When I drag and drop tab array which empty value, its value is disappear. It has error because `values` is empty.
jsonform-error
I check this value is empty. If it empty return a empty string.

**Pull request closed without merging**
