### PR TITLE
Workaround for selectfieldset in array

### PR DESCRIPTION
**Pull request by leoMehlig**
There was a bug where `selectfieldset` displayed all fields when used inside a `array`.
The problem was that the `selects` `node.childPos` was equal to the parent `childPos` when used in an `array`. I've set the childPos to be equal to the `idx` when iterating over the children.
I don't have a lot of experience with java script, so I don't know if there is a better solution.

### CODE REVIEW

**Comment by leoMehlig** [comment]
Here is a sample that used to not work and now works:
```json
{
            "schema": {
                "friends": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "title": "Friend",
                        "properties": {
                            "action": {
                                "type": "string",
                                "enum": [
                                    "a",
                                    "b"
                                ]
                            }
                        }
                    }
                },
                "test": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "title": "test",
                        "properties": {
                            "action": {
                                "type": "string",
                                "enum": [
                                    "c",
                                    "d"
                                ]
                            }
                        }
                    }
                }
            },
            "form": [
                {
                    "type": "selectfieldset",
                    "key": "test[].action",
                    "items": [
                        {
                            "type": "help",
                            "helpvalue": "test 1"
                        },
                        {
                            "type": "help",
                            "helpvalue": "test 2"
                        }
                    ]
                },
                {
                    "type": "tabarray",
                    "items": {
                        "type": "section",
                        "items": [
                            {
                                "type": "selectfieldset",
                                "key": "friends[].action",
                                "items": [
                                    {
                                        "type": "help",
                                        "helpvalue": "This should only show if a is selected"
                                    },
                                    {
                                        "type": "help",
                                        "helpvalue": "This should only show if b is selected"
                                    }
                                ]
                            }
                        ]
                    }
                }
            ]
        }
```

**Comment by tchapi** [comment]
Thanks for your PR. In order to review it, can you revert to the spaces / indentation used in the original file so that only your changes related to this bug are incorporated in it ? Thanks !

**Comment by leoMehlig** [comment]
@tchapi Sorry, I didn't notice that. My code editor did that automatically. I fixed it now.

**Comment by tchapi** [comment]
👍 thanks

**Pull request merged**
