### PR TITLE
Added support for a htmlMetaData form property.  This property can be…

### PR DESCRIPTION
**Pull request by duffar12**
… used to add additonal html metadata. The property should be specified as a hashmap. For example - form = [{"key": "myInput", "htmlMetaData": {"title": "tooltip", "style":"color: red"} this will add a tooltip and change the color of myInput

### CODE REVIEW

**Comment by tchapi** [comment]
This looks good. Can you provide a new example in `https://github.com/jsonform/jsonform/blob/master/playground/examples` and in the playground select list so that newcomers know how to use this new functionality ?

**Comment by HanxEvo** [comment]
When this feature will be released?

**Comment by tchapi** [comment]
I was waiting for the OP to provide an example for this PR.
I can make one myself this week I think, so hopefully end of week.

**Comment by tchapi** [comment]
Done. I will correct and add an example in the subsequents commits

**Comment by tchapi** [comment]
See https://github.com/jsonform/jsonform/commit/cff42c204fe5832801243595a4e2bfe7c399e129

**Comment by HanxEvo** [comment]
which are "htmlMetaData" attributes? Can I use this prop in order to add data attributes?

**Pull request merged**
