### PR TITLE
Allow numeric step any

### PR DESCRIPTION
**Pull request by michaelmairegger**

### CODE REVIEW

**Comment by tchapi** [comment]
Hello and thanks for this PR !
I would rather make an **OR** statement in the preceding line than to add a new statement altogether, can you make this change if it's ok with you ?

Something like :  

    node.schemaElement && (node.schemaElement.step > 0 || node.schemaElement.step == "any")

**Comment by michaelmairegger** [comment]
@tchapi  yes, i will do this

**Comment by michaelmairegger** [comment]
@tchapi Done

**Comment by tchapi** [comment]
Great, thanks @michaelmairegger !

**Pull request merged**
